name: PHP CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: library
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
        options: > 
          --health-cmd="mysqladmin ping -uroot -proot -h localhost || exit 1" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    env:
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASS: root
      DB_NAME: library

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mysqli, pdo_mysql

    - name: Wait for MySQL to be ready
      run: sleep 20

    - name: Import database
      run: |
        mysql -u root -proot library < database_dump.sql

    - name: Install Composer dependencies
      run: composer install

    - name: Run database connection test
      run: php -r "require 'include/db.php'; \$db = new Database(); echo 'Database connected successfully!';"

    - name: Run tests
      run: |
        echo "Add your PHPUnit or other tests here."
